### ISSUE TITLE
Compile failure in bank example

### ISSUE THREAD

**Issue by ch3pjw** [jdreaver/eventful#15]
I just tried building the bank examples via `stack`:
```
cd eventful/examples/bank
stack init
stack build
```
and got
```
[my_src_dir]/eventful/examples/bank/src/Bank/Models/Account/CommandHandler.hs:75:26: error:
    Not in scope: type constructor or class ‘CommandHandler’
```
Via quick code inspection I can't see where `CommandHandler` is supposed to come in from. Is this broken, or am I missing something?

Tried with commit 374f603c6.

**Comment by jdreaver** [comment]
I think you just need to do a `stack clean` and then a `stack build` to get everything working again. I made a recent change that replaces `Aggregate` with `CommandHandler`, so I wonder if `eventful-core` is out of date for you.

Did you just do a `git clone` before this, or did you have an old copy of the repo lying around?

> stack init

Did you mean `stack setup`? Note that `stack init` is for _creating_ stack projects.

**Comment by ch3pjw** [comment]
Yeah, going from clean and running `stack setup` worked grand. Thanks!
