### ISSUE TITLE
Not in scope: type constructor or class ‘VersionedEventStoreWriter’

### ISSUE THREAD

**Issue by revskill10** [jdreaver/eventful#25]
I installed `eventful` with `stack install eventful-core and eventful-memory`.
When running example `counter-cli`, there're errors:

```
Not in scope: type constructor or class ‘VersionedEventStoreWriter’
    Perhaps you meant ‘VersionedEventStoreReader’ (imported from Eventful.Store.Class)
   |
20 |     readAndHandleCommand :: VersionedEventStoreWriter STM CounterEvent -> VersionedEventStoreReader STM CounterEvent -> IO ()
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^

test.hs:92:34: error:
    Not in scope: type constructor or class ‘CommandHandler’
   |
92 |     type CounterCommandHandler = CommandHandler CounterState CounterEvent CounterCommand
```

How to fix it ?

**Comment by jdreaver** [comment]
Are you installing from Hackage, but then building the examples from this `git` repo? The version on Hackage will be behind what is in this repo. If you are building the examples, you should be running `stack build` from within the root directory of this repo.

**Comment by revskill10** [comment]
@jdreaver Yes, i installed from Hackage.
In this case do you know how to update package with stack right from github ?

**Comment by jdreaver** [comment]
https://docs.haskellstack.org/en/stable/yaml_configuration/#git-and-mercurial-repos
